// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewVideo struct {
	Title  string `json:"title"`
	URL    string `json:"url"`
	UserID string `json:"userId"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	GithubUserName *string  `json:"githubUserName,omitempty"`
	Videos         []*Video `json:"videos,omitempty"`
}

type Video struct {
	ID       string  `json:"id"`
	Title    string  `json:"title"`
	SubTitle *string `json:"subTitle,omitempty"`
	ThunbURL *string `json:"thunbUrl,omitempty"`
	URL      string  `json:"url"`
	Author   *User   `json:"author"`
}
