// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewVideo struct {
	Title  string `json:"title"`
	URL    string `json:"url"`
	UserID string `json:"userId"`
}

type Query struct {
}

type User struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	GithubUserName *string  `json:"githubUserName,omitempty"`
	Videos         []*Video `json:"videos,omitempty"`
}

type Video struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	URL    string `json:"url"`
	Author *User  `json:"author"`
}
